name: Automate python drug table once a month

on: push
 # schedule:
  #  - cron: "0 0 1 * *" #Once a month

jobs:
  firstjob:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          pip freeze > requirements.txt
          pip install wheel
          pip install pandas
          pip install chembl_webresource_client
      - name: execute py script # run the chemblTable.py to get the latest data
        run: |
          python chemblTable.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
         branch: main
         github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with: 
         branch: master
         base: main
      - name: Merge branches
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

        
