name: Delete old file
on:
 # push:
 schedule:
 - cron: "0 0 1 * *" #Once a month
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: https://github.com/jaaaviergarcia/drughelper/blob/main/datosChembl.tsv
